wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 30
batch_size:
  desc: null
  value: 64
weight_decay:
  desc: null
  value: 0.01
tokenizer_max_len:
  desc: null
  value: 256
attention_type:
  desc: null
  value: original_full
model_name:
  desc: null
  value: monologg/kobigbird-bert-base
num_workers:
  desc: null
  value: 0
pin_memory:
  desc: null
  value: true
patience:
  desc: null
  value: 3
warmup_ratio:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.3
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727406439
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.9
      5: 0.17.3
      6: 4.44.2
      8:
      - 4
      - 5
      13: darwin-arm64
